[package]
name = "chip_8_emulator"
version = "0.1.0"
authors = ["s3722763 <s3722763@student.rmit.edu.au>"]
edition = "2018"

[dependencies]
sdl2 = "0.32.2"
rustbox = "0.11"

[dependencies.tui]
version = "0.6"
features = ['rustbox']